SIM ?= verilator
TOPLEVEL_LANG ?= verilog

PWD=$(shell pwd)

export PYTHONPATH:=$(PWD)/counter_verif:$(PYTHONPATH)

VERILOG_SOURCES=$(PWD)/verilog/mkMAC.v

EXTRA_ARGS = --trace --trace-structs

TOPLEVEL = mkMAC
MODULE   := test_counter

include $(shell cocotb-config --makefiles)/Makefile.sim